[package]
name = "srt2webvtt"
version = "1.0.0"
authors = ["Hugues GUILLEUS <ghugues@netc.fr>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
